# .travis.yml
language: node_js
dist: trusty
sudo: required

services:
  - docker

node_js:
  - '4'
  - '6'
  - '7'

before_script:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

before_install:
  - sudo docker-compose up --build --force-recreate --remove-orphans -d
#  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
#  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
#  - npm install oracledb

script:
  - npm t

after_script:
  - sudo docker-compose down --remove-orphans

notifications:
  email: false

env:
  - KNEX_TEST_TIMEOUT=60000
#  - CXX=g++-4.8 KNEX_TEST_TIMEOUT=60000 ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE OCI_LIB_DIR=/u01/app/oracle/product/11.2.0/xe/lib LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib

matrix:
  fast_finish: true
#
# addons:
#   apt:
#     packages:
#     - g++-4.8
#     - gcc-4.8
